import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home() {
  const url = "https://pokeapi.co/api/v2/pokemon/";
  const [pokemon,setPokemon] = useState([]);
  const [data,setData] = useState([]);
  const [input,setInput] = useState("");
  const [click,setClick] = useState(false);

  useEffect(function(){
    axios.get(url + "?limit=100000&offset=0").then(function(res){
      setData(res.data.results);
    }).catch(function(err){
      console.log(err);
    })
  },[])

  useEffect(function(){
    document.addEventListener("keypress", function(event) {
      if (event.key === "Enter") {
        Submit();
      }
    });
  })

  function Submit(){
    if (document.getElementsByClassName("show")[0].className !== "hidden"){
      document.getElementsByClassName("show")[0].classList.add("hidden");
    }
    axios.get(url + input).then(function(res){
      setPokemon(res.data);
    }).catch(function(err){
      console.log(err);
    })
  }

  function Show(){
    document.getElementsByClassName("show")[0].classList.remove("hidden");
  }

  function Hide(){
    document.getElementsByClassName("show")[0].classList.add("hidden");
  }

  function Sort(){
    setClick(!click);
    console.log(click);
  }

  return (
    <div className=' flex items-center mt-3 flex-col'>
      <Head>
        <title>Poke API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className='text-2xl'>Search By Name or ID Number</p>
      <div className='flex lg:flex-row flex-col mt-2'>
        <input onChange={function(e){setInput(e.target.value)}} className=' rounded-md border-2 border-black px-2 py-1 w-80' type="text"></input>
        <button onClick={Submit} className='lg:mt-0 mt-2 hover:opacity-80 bg-blue-500 text-white px-4 py-2 rounded-lg ml-2'>Search</button>
      </div>
      <div className=' flex items-center'>
        <button onClick={Show} className=' hover:opacity-80 bg-green-500 text-white px-4 py-2 rounded-lg mt-2'>Show All Pokemon</button>
        <button onClick={Hide} className=' hover:opacity-80 bg-yellow-500 text-white px-4 py-2 rounded-lg ml-2 mt-2'>Hide All Pokemon</button>
      </div>

      <div>
        <button onClick={Sort} className=' hover:opacity-80 bg-black text-white px-4 py-2 rounded-lg ml-2 mt-2'>Sort By Alphabet</button>
      </div>

      <div className='flex flex-col items-center mt-5'>
      <p className=' font-bold text-3xl'>{pokemon.name}</p>
      {pokemon.id && 
      <div className=' text-center'>
      <img className='w-40 h-40' src={"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" + pokemon.id + ".png"}></img>
        <p className=' font-bold'>Type:</p>
        {
        pokemon.types.map(function(item){
          return (
            <div>
              <p>{item.type.name}</p>
            </div>
          )
        })
      }
      <p className=' font-bold mt-4'>Abilities :</p>
      {
        pokemon.abilities.map(function(item){
          return (
            <div>
              <p>{item.ability.name}</p>
            </div>
          )
        })
      }
            <p className=' font-bold mt-4'>Moves :</p>
      {
        pokemon.moves.map(function(item){
          return (
            <div>
              <p>{item.move.name}</p>
            </div>
          )
        })
      }
      </div>
    }

      
      </div>

      <div className='grid grid-cols-1 lg:grid-cols-4 gap-10 w-10/12 mt-10 hidden show'>
        {click ? 
                data.sort((a,b) => (a.name > b.name) ? 1 : ((b.name > a.name) ? -1 : 0)).map(function(item,index ){
                  const result = item.url.match(/\d+/g);
                  return (
                    <div className=' flex flex-col items-center'>
                      <p>{item.name}</p>
                      <img src={"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" + (result[1]) + ".png"}></img>
                    </div>
                  )
                })
                :
                data.map(function(item,index ){
                  const result = item.url.match(/\d+/g);
                  return (
                    <div className=' flex flex-col items-center'>
                      <p>{item.name}</p>
                      <img src={"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" + (result[1]) + ".png"}></img>
                    </div>
                  )
                })
      }
      </div>

    </div>
  )
}
